import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return ( 
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar"> 
        <Link href="/" className="logo">nanobot</Link> 
        <Link href="/list">List</Link> 
        
        {
          !session?.user ?<LoginBtn/> : null
        } 
        {
          session?.user ? <span className="user-email">{session.user.name}님 환영합니다.</span> : null
        }
          
          
      </div>  
        {children}
      </body>
    </html>
  );
}
